// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHYQ1sCQg7y-_p0k56bxpH4uZ7vDSw0c',
    appId: '1:348117983515:web:4af4e150669df5b34db3be',
    messagingSenderId: '348117983515',
    projectId: 'quizapp2-56f35',
    authDomain: 'quizapp2-56f35.firebaseapp.com',
    storageBucket: 'quizapp2-56f35.appspot.com',
    measurementId: 'G-5N8PVG5572',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvODlhf32YsdoVkpcjsYPPJ_G1gIrIdcM',
    appId: '1:348117983515:android:1c67451278fbaa764db3be',
    messagingSenderId: '348117983515',
    projectId: 'quizapp2-56f35',
    storageBucket: 'quizapp2-56f35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuLPC6NMOxszwsmBNpD_bPKmz8GNHCPLU',
    appId: '1:348117983515:ios:f83b3c6b9fabb1d74db3be',
    messagingSenderId: '348117983515',
    projectId: 'quizapp2-56f35',
    storageBucket: 'quizapp2-56f35.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuLPC6NMOxszwsmBNpD_bPKmz8GNHCPLU',
    appId: '1:348117983515:ios:f83b3c6b9fabb1d74db3be',
    messagingSenderId: '348117983515',
    projectId: 'quizapp2-56f35',
    storageBucket: 'quizapp2-56f35.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHYQ1sCQg7y-_p0k56bxpH4uZ7vDSw0c',
    appId: '1:348117983515:web:a44bb13337138ec84db3be',
    messagingSenderId: '348117983515',
    projectId: 'quizapp2-56f35',
    authDomain: 'quizapp2-56f35.firebaseapp.com',
    storageBucket: 'quizapp2-56f35.appspot.com',
    measurementId: 'G-REPDH9HCZC',
  );
}
